// Assembles the web app into src-tauri/web so tauri-build can embed it.
//
// The data bundles are generated by `node tools/build-data.mjs`; this script
// fails loudly if they are missing, rather than shipping an app whose content
// silently never loads.

use std::path::{Path, PathBuf};

fn main() {
    let manifest = std::env::var("CARGO_MANIFEST_DIR").expect("manifest dir");
    let root = Path::new(&manifest)
        .parent()
        .expect("project root")
        .to_path_buf();
    let out = Path::new(&manifest).join("web");

    let files: &[&str] = &[
        "index.html",
        "styles.css",
        "app.js",
        "sw.js",
        "manifest.webmanifest",
        "icon.svg",
        "icon-maskable.svg",
    ];

    for file in files {
        let src = root.join(file);
        assert!(src.is_file(), "missing {file} - run from the project root");
        copy(&src, &out.join(file));
        println!("cargo:rerun-if-changed={}", src.display());
    }

    for dir in ["js", "data"] {
        let src = root.join(dir);
        assert!(
            src.is_dir(),
            "missing {dir}/ - run `node tools/build-data.mjs` first"
        );
        copy_tree(&src, &out.join(dir));
        println!("cargo:rerun-if-changed={}", src.display());
    }

    // The service worker only makes sense for the hosted app; inside the binary
    // every file is already local, and a SW registered on a custom scheme can
    // interfere with first paint.
    let _ = std::fs::remove_file(out.join("sw.js"));

    tauri_build::build();
}

fn copy(src: &Path, dest: &Path) {
    if let Some(parent) = dest.parent() {
        std::fs::create_dir_all(parent).expect("create output dir");
    }
    std::fs::copy(src, dest).unwrap_or_else(|e| panic!("copy {}: {e}", src.display()));
}

fn copy_tree(src: &Path, dest: &Path) {
    std::fs::create_dir_all(dest).expect("create output dir");
    for entry in std::fs::read_dir(src).expect("read source dir") {
        let entry = entry.expect("dir entry");
        let path = entry.path();
        let target = dest.join(entry.file_name());
        if path.is_dir() {
            copy_tree(&path, &target);
        } else {
            copy(&path, &target);
        }
    }
}

/// Kept for clarity in the log line below.
#[allow(dead_code)]
fn describe(path: &PathBuf) -> String {
    path.display().to_string()
}