// Authored kana reference content: romaji + mnemonics.
// Stroke order data comes from zhengkyl/strokesvg (Klee One font, OFL) at build time.

export const HIRAGANA = [
  { c: 'あ', r: 'a', m: 'An <b>antenna</b> — the crossbar on top catches the signal.' },
  { c: 'い', r: 'i', m: 'Two <b>eels</b> swimming side by side.' },
  { c: 'う', r: 'u', m: 'A roof over a face, looking <b>up</b>.' },
  { c: 'え', r: 'e', m: 'A bird with an <b>elegant</b> wing feather.' },
  { c: 'お', r: 'o', m: 'A curled <b>over</b>hand holding a ball.' },
  { c: 'か', r: 'ka', m: 'A <b>kayak</b> paddle and its <b>knot</b> of rope.' },
  { c: 'き', r: 'ki', m: 'A <b>key</b> with its teeth cut in two.' },
  { c: 'く', r: 'ku', m: 'A <b>kite</b> shape, pointing back the way it came.' },
  { c: 'け', r: 'ke', m: 'A <b>kettle</b> with a handle and a spout.' },
  { c: 'こ', r: 'ko', m: '<b>Cow</b> saying moo — two stacked fences.' },
  { c: 'さ', r: 'sa', m: 'A <b>sakura</b> branch, hanging off a hook.' },
  { c: 'し', r: 'shi', m: 'A <b>shrimp</b> curled into a comma.' },
  { c: 'す', r: 'su', m: 'A <b>sword</b> of sushi: a needle threading through.' },
  { c: 'せ', r: 'se', m: 'Sitting up <b>straight</b> to <b>see</b> over the crowd.' },
  { c: 'そ', r: 'so', m: '<b>So</b> close — a zig-zag hem of a sock.' },
  { c: 'た', r: 'ta', m: 'A <b>table</b> with a leg kicking out to the side.' },
  { c: 'ち', r: 'chi', m: 'A <b>check</b> mark over a cross — a chicken scratching.' },
  { c: 'つ', r: 'tsu', m: 'The shape of <b>Tsu</b> himself, swimming a <b>c</b>omma.' },
  { c: 'て', r: 'te', m: 'A <b>tent</b>, or a hand reaching out.' },
  { c: 'と', r: 'to', m: '<b>To</b> the left: a cow horn and a fin.' },
  { c: 'な', r: 'na', m: 'A <b>noose</b> with the rope knotted off to the side.' },
  { c: 'に', r: 'ni', m: 'Two rails of a <b>stairway</b> — に looks like stairs.' },
  { c: 'ぬ', r: 'nu', m: 'A <b>cat</b> batting at a ball of yarn.' },
  { c: 'ね', r: 'ne', m: 'A <b>snake</b> made of rope — the root of a <b>tree</b>.' },
  { c: 'の', r: 'no', m: '<b>No!</b> A single loop of a lasso.' },
  { c: 'は', r: 'ha', m: 'A <b>hat</b> with a brim and a face below it.' },
  { c: 'ひ', r: 'hi', m: 'A <b>door</b> with a handle, or a <b>smile</b>.' },
  { c: 'ふ', r: 'fu', m: 'A <b>fountain</b> spouting from a pipe.' },
  { c: 'へ', r: 'he', m: 'A <b>hill</b>, or a mountain peak.' },
  { c: 'ほ', r: 'ho', m: 'A <b>candle</b> flame on a stand.' },
  { c: 'ま', r: 'ma', m: 'Two arrows crossed over a <b>map</b> of a field.' },
  { c: 'み', r: 'mi', m: 'A katana <b>blade</b>, drawn to the left.' },
  { c: 'む', r: 'mu', m: 'A bull\u2019s <b>eye</b> with a tail flicking away.' },
  { c: 'め', r: 'me', m: 'A <b>frame</b> around an eye with an <b>eyebrow</b>.' },
  { c: 'も', r: 'mo', m: 'A <b>moat</b> with two stakes driven into it.' },
  { c: 'や', r: 'ya', m: 'A <b>slingshot</b> pulled back and ready.' },
  { c: 'ゆ', r: 'yu', m: 'A <b>bath</b> with a plug in the drain.' },
  { c: 'よ', r: 'yo', m: 'A <b>yoyo</b> string and a hand holding it.' },
  { c: 'ら', r: 'ra', m: 'A <b>racoon</b> curled up, tail and all.' },
  { c: 'り', r: 'ri', m: 'A <b>river</b> with two banks running past.' },
  { c: 'る', r: 'ru', m: 'A <b>loop</b> and a tail — the only kana ending in ru.' },
  { c: 'れ', r: 're', m: 'A <b>ribbon</b> and a bow tied on a present.' },
  { c: 'ろ', r: 'ro', m: 'A <b>road</b> curving out of sight.' },
  { c: 'わ', r: 'wa', m: 'A <b>wheel</b> spinning on a shaft.' },
  { c: 'を', r: 'wo', m: 'A <b>hair bun</b> tied in a loop — used as a particle.' },
  { c: 'ん', r: 'n', m: 'A <b>nose</b> in profile. One stroke, no loops.' },
];

export const KATAKANA = [
  { c: 'ア', r: 'a', m: 'An <b>angle</b>, or the ace of cards.' },
  { c: 'イ', r: 'i', m: 'Two strokes cutting through, like a katana slash.' },
  { c: 'ウ', r: 'u', m: 'A roof over a face, looking up.' },
  { c: 'エ', r: 'e', m: 'The letter <b>E</b> — <b>e</b>very sharp.' },
  { c: 'オ', r: 'o', m: 'A <b>ox</b> with a horn and a tail.' },
  { c: 'カ', r: 'ka', m: 'A <b>katana</b>, or a <b>carabiner</b> clipped on.' },
  { c: 'キ', r: 'ki', m: 'A <b>key</b>, drawn big and square.' },
  { c: 'ク', r: 'ku', m: 'A <b>kite</b>, or the nose of an arrow.' },
  { c: 'ケ', r: 'ke', m: 'A <b>kite</b> from the side, or a <b>gate</b>.' },
  { c: 'コ', r: 'ko', m:A => `A <b>corner</b> of a room. ${A}` },
  { c: 'サ', r: 'sa', m: 'A stick figure raising both arms in <b>salsa</b>.' },
  { c: 'シ', r: 'shi', m: 'A <b>swimmer</b> doing three strokes, head first.' },
  { c: 'ス', r: 'su', m: 'A <b>stoop</b> in the wind, or a <b>sneaker</b>.' },
  { c: 'セ', r: 'se', m: 'A hand held up to <b>see</b> who is behind it.' },
  { c: 'ソ', r: 'so', m: 'A <b>comb</b> drawn at an angle.' },
  { c: 'タ', r: 'ta', m: 'The letter <b>T</b> with a flick.' },
  { c: 'チ', r: 'chi', m: 'A <b>check</b> mark over a small cross.' },
  { c: 'ツ', r: 'tsu', m: 'Two <b>teeth</b> and a tongue — careful, ッ is small.' },
  { c: 'テ', r: 'te', m: 'A <b>temple</b> roof, or an upturned hand.' },
  { c: 'ト', r: 'to', m: 'A <b>toad</b> squatting in the corner.' },
  { c: 'ナ', r: 'na', m: 'A <b>knot</b> with the rope running off to the side.' },
  { c: 'ニ', r: 'ni', m: 'Two rails of a <b>stairway</b>.' },
  { c: 'ヌ', r: 'nu', m: 'A knot of <b>nylon</b> rope.' },
  { c: 'ネ', r: 'ne', m: 'A <b>mouse cursor</b> pointing right.' },
  { c: 'ノ', r: 'no', m: 'One long slash — a <b>no</b>-sign in a hurry.' },
  { c: 'ハ', r: 'ha', m: 'A <b>hut</b>, or two feet mid-stride.' },
  { c: 'ヒ', r: 'hi', m: 'A <b>ladder</b> seen from the side.' },
  { c: 'フ', r: 'fu', m: 'A <b>flag</b> on a bent pole.' },
  { c: 'ヘ', r: 'he', m: 'A mountain peak, the shape of <b>he</b>' },
  { c: 'ホ', r: 'ho', m: 'A <b>candle</b> with wings spread.' },
  { c: 'マ', r: 'ma', m: 'Two arrows meeting at a <b>mark</b>.' },
  { c: 'ミ', r: 'mi', m: 'Three rails of a <b>river</b> bridge.' },
  { c: 'ム', r: 'mu', m: 'A <b>museum</b> pediment seen from the side.' },
  { c: 'メ', r: 'me', m: 'A <b>check</b> mark and a <b>measure</b> slash.' },
  { c: 'モ', r: 'mo', m: 'A <b>motor</b> with two shafts.' },
  { c: 'ヤ', r: 'ya', m: 'A <b>yacht</b> sail, or a slingshot.' },
  { c: 'ユ', r: 'yu', m: 'A <b>yule</b> log, or a boat seen end-on.' },
  { c: 'ヨ', r: 'yo', m: 'A <b>comb</b> with three teeth — three horizontal strokes.' },
  { c: 'ラ', r: 'ra', m: 'A <b>rabbit</b> with ears and a tail.' },
  { c: 'リ', r: 'ri', m: 'A <b>rake</b>, or two <b>rails</b>.' },
  { c: 'ル', r: 'ru', m: 'A <b>loop</b> and a tail, like る.' },
  { c: 'レ', r: 're', m: 'A <b>ribbon</b>, or a <b>slide</b> down a chute.' },
  { c: 'ロ', r: 'ro', m: 'A <b>room</b>, or an open <b>mouth</b>.' },
  { c: 'ワ', r: 'wa', m: 'A <b>wheel</b> and a shaft, drawn square.' },
  { c: 'ヲ', r: 'wo', m: 'A <b>rope</b> looped around a post.' },
  { c: 'ン', r: 'n', m: 'A single <b>nose</b> stroke, rising to the right.' },
];

// Dakuten / handakuten and small kana get generated from the base table so the
// romaji rules stay in one place.
export const DERIVED = [
  { c: 'が', base: 'か', r: 'ga' }, { c: 'ぎ', base: 'き', r: 'gi' },
  { c: 'ぐ', base: 'く', r: 'gu' }, { c: 'げ', base: 'け', r: 'ge' },
  { c: 'ご', base: 'こ', r: 'go' }, { c: 'ざ', base: 'さ', r: 'za' },
  { c: 'じ', base: 'し', r: 'ji' }, { c: 'ず', base: 'す', r: 'zu' },
  { c: 'ぜ', base: 'せ', r: 'ze' }, { c: 'ぞ', base: 'そ', r: 'zo' },
  { c: 'だ', base: 'た', r: 'da' }, { c: 'ぢ', base: 'ち', r: 'ji' },
  { c: 'づ', base: 'つ', r: 'zu' }, { c: 'で', base: 'て', r: 'de' },
  { c: 'ど', base: 'と', r: 'do' }, { c: 'ば', base: 'は', r: 'ba' },
  { c: 'び', base: 'ひ', r: 'bi' }, { c: 'ぶ', base: 'ふ', r: 'bu' },
  { c: 'べ', base: 'へ', r: 'be' }, { c: 'ぼ', base: 'ほ', r: 'bo' },
  { c: 'ぱ', base: 'は', r: 'pa' }, { c: 'ぴ', base: 'ひ', r: 'pi' },
  { c: 'ぷ', base: 'ふ', r: 'pu' }, { c: 'ぺ', base: 'へ', r: 'pe' },
  { c: 'ぽ', base: 'ほ', r: 'po' },
  { c: 'が', base: 'カ', r: 'ga' }, { c: 'ギ', base: 'キ', r: 'gi' },
  { c: 'グ', base: 'ク', r: 'gu' }, { c: 'ゲ', base: 'ケ', r: 'ge' },
  { c: 'ゴ', base: 'コ', r: 'go' }, { c: 'ザ', base: 'サ', r: 'za' },
  { c: 'ジ', base: 'シ', r: 'ji' }, { c: 'ズ', base: 'ス', r: 'zu' },
  { c: 'ゼ', base: 'セ', r: 'ze' }, { c: 'ゾ', base: 'ソ', r: 'zo' },
  { c: 'ダ', base: 'タ', r: 'da' }, { c: 'ヂ', base: 'チ', r: 'ji' },
  { c: 'ヅ', base: 'ツ', r: 'zu' }, { c: 'デ', base: 'テ', r: 'de' },
  { c: 'ド', base: 'ト', r: 'do' }, { c: 'バ', base: 'ハ', r: 'ba' },
  { c: 'ビ', base: 'ヒ', r: 'bi' }, { c: 'ブ', base: 'フ', r: 'bu' },
  { c: 'ベ', base: 'ヘ', r: 'be' }, { c: 'ボ', base: 'ホ', r: 'bo' },
  { c: 'パ', base: 'ハ', r: 'pa' }, { c: 'ピ', base: 'ヒ', r: 'pi' },
  { c: 'プ', base: 'フ', r: 'pu' }, { c: 'ペ', base: 'ヘ', r: 'pe' },
  { c: 'ポ', base: 'ホ', r: 'po' },
  { c: 'ゔ', base: 'う', r: 'vu' }, { c: 'ヴ', base: 'ウ', r: 'vu' },
];

// Small kana: the romaji is the same, only the size changes.
export const SMALL = [
  { c: 'ぁ', base: 'あ' }, { c: 'ぃ', base: 'い' }, { c: 'ぅ', base: 'う' },
  { c: 'ぇ', base: 'え' }, { c: 'ぉ', base: 'お' }, { c: 'ゃ', base: 'や' },
  { c: 'ゅ', base: 'ゆ' }, { c: 'ょ', base: 'よ' }, { c: 'ゎ', base: 'わ' },
  { c: 'ァ', base: 'ア' }, { c: 'ィ', base: 'イ' }, { c: 'ゥ', base: 'ウ' },
  { c: 'ェ', base: 'エ' }, { c: 'ォ', base: 'オ' }, { c: 'ャ', base: 'ヤ' },
  { c: 'ュ', base: 'ユ' }, { c: 'ョ', base: 'ヨ' }, { c: 'ヮ', base: 'ワ' },
  { c: 'ヶ', base: 'ケ' }, { c: 'ヵ', base: 'カ' },
];